export const GOOGLE_FONTS = [
  { name: "Montserrat", category: "sans-serif" },
  { name: "Roboto", category: "sans-serif" },
  { name: "Open Sans", category: "sans-serif" },
  { name: "Lato", category: "sans-serif" },
  { name: "Poppins", category: "sans-serif" },
  { name: "Inter", category: "sans-serif" },
  { name: "Oswald", category: "sans-serif" },
  { name: "Bebas Neue", category: "display" },
  { name: "Anton", category: "sans-serif" },
  { name: "Teko", category: "sans-serif" },
  { name: "Rajdhani", category: "sans-serif" },
  { name: "Righteous", category: "display" },
  { name: "Racing Sans One", category: "display" },
  { name: "Russo One", category: "sans-serif" },
  { name: "Chakra Petch", category: "sans-serif" },
  { name: "Bungee", category: "display" },
  { name: "Press Start 2P", category: "display" },
  { name: "Orbitron", category: "sans-serif" },
  { name: "Audiowide", category: "display" },
  { name: "Black Ops One", category: "display" },
  { name: "Staatliches", category: "display" },
  { name: "Rubik Mono One", category: "sans-serif" },
  { name: "Viga", category: "sans-serif" },
  { name: "VT323", category: "monospace" },
  { name: "Share Tech Mono", category: "monospace" },
  { name: "Wallpoet", category: "display" },
  { name: "Faster One", category: "display" },
  { name: "Michroma", category: "sans-serif" },
  { name: "Allerta Stencil", category: "sans-serif" },
  { name: "Graduate", category: "display" }
];
